### ISSUE TITLE
Doesn't work on Windows 10 MS Store version

### ISSUE THREAD

**Issue by JOY** [jszklarz-haventec/makeitdark#12]
`Traceback (most recent call last):
  File "makeitdark.py", line 69, in <module>
    most_recent = sorted([slack_version for slack_version in os.listdir(slack_root_path) if slack_version.startswith("app-") and os.path.isdir(os.path.join(slack_root_path, slack_version))], reverse=True)[0]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\USER\\AppData\\Local\\slack'`

**Comment by LostConnection** [comment]
Good find, I believe this is because the MS Store installation dir is different from a direct installation from the Slack website. The same happens if you install Slack via snap or some other manager.
Will just have to add the different paths to the script to determine where to inject the styles.

**Comment by LostConnection** [comment]
> `Traceback (most recent call last): File "makeitdark.py", line 69, in <module> most_recent = sorted([slack_version for slack_version in os.listdir(slack_root_path) if slack_version.startswith("app-") and os.path.isdir(os.path.join(slack_root_path, slack_version))], reverse=True)[0] FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\USER\\AppData\\Local\\slack'`

@LeGiangAnh 
Would you be able to provide me with the directory where your slack install actually exists when installing via the MS Store?

**Comment by JOY** [comment]
This one C:\Program Files\WindowsApps\91750D7E.Slack_3.3.3.0_x64__8she8kybcnzg4\app
Please notice that Windows seem prevent me from changing the file in this folder. I tried to modify or override the css file but didn't work.

**Comment by LostConnection** [comment]
> This one C:\Program Files\WindowsApps\91750D7E.Slack_3.3.3.0_x64__8she8kybcnzg4\app
> Please notice that Windows seem prevent me from changing the file in this folder. I tried to modify or override the css file but didn't work.

Mmmm I see. Looks like the permissions of the WindowsApps folder are locked down. I'll have a think about what I want to do about this. I will have a fiddle around with this once I have access to my windows machine.
